### ISSUE TITLE
Announcement: Now on Helm Hub

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/helm-chart#22]
The chart has now been registered on Helm Hub in helm/hub#171.

https://hub.helm.sh/charts/dask/dask

![image](https://user-images.githubusercontent.com/1610850/68216096-43619c00-ffd8-11e9-9486-cb95b7304df2.png)

**Comment by mrocklin** [comment]
Thanks Jacob!  Is this something that we should blog or tweet about?  Do
you have access to the twitter account?  If not, we can probably make that
happen.

**Comment by jacobtomlinson** [comment]
Possibly! Given that this chart already existed and has been moved to a new home there isn't a huge amount to shout about. However if there isn't any existing content about it then maybe a how-to would be good?

**Comment by mrocklin** [comment]
The only content we have is the documentation.  This gets pointed to fairly
well because the "cloud" links currently highlight it.  Anecdotally I get
the impression that the Dask helm chart used decently often, but maybe this
is just that helm users are more likely to feel comfortable raising issues.

Any content would be good.  Even if there isn't new content, periodically
finding reasons to tweet about it is probably good.
