### ISSUE TITLE
hpa config

### ISSUE THREAD

**Issue by shaunc** [dask/helm-chart#56]
I saw in the now deprecated stable/dask-distributed chart maxReplicas config for the horizontal pod autoscaler. That doesn't seem to have made it here. Is HPA supported?

**Comment by jacobtomlinson** [comment]
`stable/dask-distributed` is a very old chart. The deprecation notice points to `stable/dask` which has also been deprecated in favour of `dask/helm-chart` (here).

To answer your question Dask manages it's own scaling. Mixing something like HPA with Dask's own scaling techniques often results in failed computations or recalculation. This is due to the way Dask manages its own state and selectively removes workers.

**Comment by shaunc** [comment]
I understand -- thanks! Is there anything to keep in mind when using Dask with cluster autoscaling?

**Comment by jacobtomlinson** [comment]
If you are using the Dask Helm chart autoscaling is not currently supported. You can manually increase and decrease the number of workers by modifying the deployment with `kubectl`, but scaling down should only be done when the cluster is idle.

I'm going to close this issue now but I'm happy to answer specific questions if you have them, preferably on Stack Overflow 😄.
